package exceptionHandling;

public class Runtime_ArithmeticException {
public static void main(String[] args) {
	try
	{
		int a=10/0;
	}
	catch(ArithmeticException a)
	{
		System.out.println("Exception handled..!");
	}
}
}
